version: '3'
services:
  shorten:
    image: dev_linker_image:test1
    build: .
    restart: on-failure
    environment:
      - DB_VENDOR=sqlite
      - DB_FILE=/data/db.sqlite3
      - SESSION_DB_FILE_LOC=/data/
      - SESSION_DB_FILE_NAME=sessions.sqlite3
      - CLIENT_SECRET
    ports:
      - "9215:9215"
    volumes:
      - ./config.js:/data/config.js
      - ./db.sqlite3:/data/db.sqlite3
      - ./sessions.sqlite3:/data/sessions.sqlite3
    env_file:
      - .env
